// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker/worker.proto

package worker_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetDataRequest struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataRequest) Reset()         { *m = SetDataRequest{} }
func (m *SetDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetDataRequest) ProtoMessage()    {}
func (*SetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b12885d1d036f320, []int{0}
}

func (m *SetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataRequest.Unmarshal(m, b)
}
func (m *SetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataRequest.Marshal(b, m, deterministic)
}
func (m *SetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataRequest.Merge(m, src)
}
func (m *SetDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetDataRequest.Size(m)
}
func (m *SetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataRequest proto.InternalMessageInfo

func (m *SetDataRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SetDataRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SetDataReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataReply) Reset()         { *m = SetDataReply{} }
func (m *SetDataReply) String() string { return proto.CompactTextString(m) }
func (*SetDataReply) ProtoMessage()    {}
func (*SetDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b12885d1d036f320, []int{1}
}

func (m *SetDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataReply.Unmarshal(m, b)
}
func (m *SetDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataReply.Marshal(b, m, deterministic)
}
func (m *SetDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataReply.Merge(m, src)
}
func (m *SetDataReply) XXX_Size() int {
	return xxx_messageInfo_SetDataReply.Size(m)
}
func (m *SetDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataReply proto.InternalMessageInfo

func (m *SetDataReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SetDataReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetDataRequest struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b12885d1d036f320, []int{2}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type GetDataReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataReply) Reset()         { *m = GetDataReply{} }
func (m *GetDataReply) String() string { return proto.CompactTextString(m) }
func (*GetDataReply) ProtoMessage()    {}
func (*GetDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b12885d1d036f320, []int{3}
}

func (m *GetDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReply.Unmarshal(m, b)
}
func (m *GetDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReply.Marshal(b, m, deterministic)
}
func (m *GetDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReply.Merge(m, src)
}
func (m *GetDataReply) XXX_Size() int {
	return xxx_messageInfo_GetDataReply.Size(m)
}
func (m *GetDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReply proto.InternalMessageInfo

func (m *GetDataReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SetDataRequest)(nil), "worker.api.SetDataRequest")
	proto.RegisterType((*SetDataReply)(nil), "worker.api.SetDataReply")
	proto.RegisterType((*GetDataRequest)(nil), "worker.api.GetDataRequest")
	proto.RegisterType((*GetDataReply)(nil), "worker.api.GetDataReply")
}

func init() { proto.RegisterFile("worker/worker.proto", fileDescriptor_b12885d1d036f320) }

var fileDescriptor_b12885d1d036f320 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xcf, 0x2f, 0xca,
	0x4e, 0x2d, 0xd2, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x5c, 0x50, 0x5e, 0x62,
	0x41, 0xa6, 0x92, 0x1d, 0x17, 0x5f, 0x70, 0x6a, 0x89, 0x4b, 0x62, 0x49, 0x62, 0x50, 0x6a, 0x61,
	0x69, 0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x6b, 0x10, 0x98, 0x2d, 0x24, 0xc1, 0xc5, 0x9e, 0x9c, 0x9f, 0x57, 0x92, 0x9a, 0x57, 0x22,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x2a, 0x59, 0x70, 0xf1, 0xc0, 0xf5, 0x17, 0xe4,
	0x54, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0x97, 0x24, 0x96, 0x94, 0x16, 0x43, 0xf5, 0x43, 0x79, 0x42,
	0x02, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9, 0x50, 0xdd, 0x20, 0xa6, 0x92, 0x0a, 0x17, 0x9f, 0x3b, 0x41,
	0x9b, 0x95, 0x14, 0xb8, 0x78, 0xdc, 0x91, 0xcd, 0x87, 0x9a, 0xc3, 0x08, 0x37, 0xc7, 0x68, 0x2a,
	0x23, 0x17, 0x6f, 0x38, 0xd8, 0x43, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x8e, 0x5c,
	0xec, 0x50, 0x37, 0x09, 0x49, 0xe9, 0x21, 0xfc, 0xaa, 0x87, 0xea, 0x51, 0x29, 0x09, 0xac, 0x72,
	0x05, 0x39, 0x95, 0x4a, 0x0c, 0x20, 0x23, 0xdc, 0xb1, 0x19, 0xe1, 0x8e, 0xc7, 0x08, 0x77, 0x14,
	0x23, 0x92, 0xd8, 0xc0, 0x81, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xaf, 0xb7, 0x97,
	0x83, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerServiceClient interface {
	SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataReply, error)
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataReply, error)
}

type workerServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorkerServiceClient(cc *grpc.ClientConn) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataReply, error) {
	out := new(SetDataReply)
	err := c.cc.Invoke(ctx, "/worker.api.WorkerService/SetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataReply, error) {
	out := new(GetDataReply)
	err := c.cc.Invoke(ctx, "/worker.api.WorkerService/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
type WorkerServiceServer interface {
	SetData(context.Context, *SetDataRequest) (*SetDataReply, error)
	GetData(context.Context, *GetDataRequest) (*GetDataReply, error)
}

func RegisterWorkerServiceServer(s *grpc.Server, srv WorkerServiceServer) {
	s.RegisterService(&_WorkerService_serviceDesc, srv)
}

func _WorkerService_SetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.api.WorkerService/SetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SetData(ctx, req.(*SetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.api.WorkerService/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "worker.api.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetData",
			Handler:    _WorkerService_SetData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _WorkerService_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker/worker.proto",
}
